name: Build and Push echo-server Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'echo-server/**'
      - '.github/workflows/echo-server-docker.yml'

permissions:
  contents: read

jobs:
  docker:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./echo-server
          file: ./echo-server/Dockerfile
          push: true
          tags: |
            ikupczynski/echo-server:latest
            ikupczynski/echo-server:${{ github.sha }}

