name: Test echo-server

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'echo-server/**'
      - 'selfsigned-gen/**'
      - '.github/workflows/echo-server-tests.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'echo-server/**'
      - 'selfsigned-gen/**'
      - '.github/workflows/echo-server-tests.yml'

jobs:
  test:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: echo-server/go.mod

      - name: Run unit tests
        working-directory: echo-server
        run: go test -v -race .

      - name: Run integration tests
        working-directory: echo-server
        run: go test -v -race -tags integration -timeout 5m .

      - name: Unit test coverage
        working-directory: echo-server
        run: |
          go test -coverprofile=unit.cover -covermode=atomic .
          go tool cover -func=unit.cover

      - name: Integration test coverage
        working-directory: echo-server
        run: |
          go test -tags integration -coverprofile=integration.cover -covermode=atomic .
          go tool cover -func=integration.cover
