name: Build and Push echo-server Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'echo-server/**'
      - '.github/workflows/echo-server-docker.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  binaries:
    name: Build Cross-Platform Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: echo-server/go.mod

      - name: Build binary
        working-directory: echo-server
        run: |
          mkdir -p ../dist
          OUTPUT=../dist/echo-server-${{ matrix.goos }}-${{ matrix.goarch }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 \
            go build -trimpath -ldflags "-s -w" -o "${OUTPUT}" .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: echo-server-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/echo-server-${{ matrix.goos }}-${{ matrix.goarch }}
          if-no-files-found: error

  docker:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: binaries
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./echo-server
          file: ./echo-server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: |
            ikupczynski/echo-server:latest
            ikupczynski/echo-server:${{ github.sha }}

