name: echo-server Tests

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'echo-server/**'
      - 'selfsigned-gen/**'
      - '.github/workflows/echo-server-tests.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'echo-server/**'
      - 'selfsigned-gen/**'
      - '.github/workflows/echo-server-tests.yml'

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      
      - name: Build selfsigned-gen (dependency for tests)
        run: |
          cd selfsigned-gen
          GO111MODULE=off go build -o selfsigned-gen
          echo "$PWD" >> $GITHUB_PATH
        
      - name: Run unit tests
        working-directory: echo-server
        run: go test -v -race -run '^Test[^I]' .
      
      - name: Run integration tests
        working-directory: echo-server
        run: go test -v -race -timeout 5m .
      
      - name: Generate coverage report
        working-directory: echo-server
        run: |
          go test -coverprofile=coverage.txt -covermode=atomic .
          go tool cover -func=coverage.txt
